"use client";
import { useId, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, Download, LockKeyhole, Save, Trash2, Printer, RotateCcw } from "lucide-react";
import { useTier } from "@/context/TierContext";
import { useLocalState } from "@/lib/useLocalState";
import { BOUNDS, DEFAULTS, LIMITS, calculate, sensitivity, money, isInputs, isScenarios, downloadCSV, type Inputs, type Scenario } from "@/lib/engine";
import { Button, Reveal } from "./Primitives";
const presets: { name: string; inputs: Inputs }[] = [
  { name: "Website", inputs: DEFAULTS },
  { name: "Brand sprint", inputs: { ...DEFAULTS, hours: 24, rate: 90, expenses: 100, overhead: 200, margin: 40 } },
  { name: "Retainer", inputs: { ...DEFAULTS, hours: 60, rate: 75, expenses: 150, overhead: 500, margin: 30 } },
];
function Field({ label, value, field, suffix = "", locked = false, onChange }: { label: string; value: number; field: keyof Inputs; suffix?: string; locked?: boolean; onChange: (key: keyof Inputs, value: number) => void }) {
  const id = useId(); const [min, max, step] = BOUNDS[field];
  return <div className={`field ${locked ? "locked-field" : ""}`}><div className="between"><label htmlFor={id}>{label}</label>{locked && <LockKeyhole size={13} aria-label="Requires a higher tier" />}</div><div className="input-shell"><input id={id} type="number" min={min} max={max} step={step} disabled={locked} value={value} onChange={event => { const n = event.target.valueAsNumber; if (Number.isFinite(n)) onChange(field, Math.min(max, Math.max(min, field === "team" ? Math.round(n) : n))); }} /><span className="mono muted small">{suffix}</span></div><input type="range" aria-label={`${label} slider`} min={min} max={max} step={step} disabled={locked} value={value} onChange={event => onChange(field, Number(event.target.value))} /></div>;
}
function Upgrade({ plan, children }: { plan: "Plus" | "Pro"; children: React.ReactNode }) {
  const { selectTier } = useTier();
  return <motion.div className="upgrade" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><LockKeyhole size={18} /><div><b>{plan} decision tools</b><p className="small muted">{children}</p></div><Button onClick={() => selectTier(plan)}>Try {plan}<ArrowUpRight size={14} /></Button></motion.div>;
}
export default function SaaSAppWorkspace() {
  const { tier, ready, storageOK } = useTier();
  const [inputs, setInputs, inputsReady, inputsOK] = useLocalState<Inputs>("marginpilot:inputs:v1", DEFAULTS, isInputs);
  const [scenarios, setScenarios, scenariosReady, scenariosOK] = useLocalState<Scenario[]>("marginpilot:scenarios:v1", [], isScenarios);
  const [name, setName] = useState("My next project");
  const [tab, setTab] = useState<"quote" | "risk" | "capacity">("quote");
  const [notice, setNotice] = useState("");
  const [compareId, setCompareId] = useState("");
  const plus = tier !== "Free"; const pro = tier === "Pro";
  const active = ready && inputsReady && scenariosReady;
  const result = calculate(inputs, tier); const rows = sensitivity(inputs, tier);
  const accessible = scenarios.slice(0, LIMITS[tier]);
  const compare = plus ? accessible.find(s => s.id === compareId) : undefined;
  const compared = compare ? calculate(compare.inputs, tier) : undefined;
  function change(key: keyof Inputs, value: number) { setInputs(current => ({ ...current, [key]: value })); }
  function save() {
    if (!active) return;
    if (scenarios.length >= LIMITS[tier]) { setNotice(`Your ${tier} plan allows ${LIMITS[tier]} saved scenarios. Delete a scenario or try a higher tier.`); return; }
    setScenarios(current => [...current, { id: crypto.randomUUID(), name: name.trim() || "Untitled project", inputs: { ...inputs }, savedAt: new Date().toISOString() }]);
    setNotice("Scenario saved in this browser. It includes your current inputs.");
  }
  function exportReport() {
    if (!pro || !active) return;
    downloadCSV([
      ["MarginPilot project report", name.trim() || "Untitled project"], ["Currency", "USD"], ["Demo tier", tier],
      ["Effort hours", inputs.hours], ["Internal hourly cost", inputs.rate], ["Direct expenses", inputs.expenses], ["Allocated overhead", inputs.overhead],
      ["Target margin percent", inputs.margin], ["Contingency percent", inputs.contingency], ["Base cost", result.cost], ["Reserve", result.reserve],
      ["Recommended quote", Number(result.quote.toFixed(2))], ["Modeled profit", Number(result.profit.toFixed(2))],
      ["Weekly productive hours per person", inputs.weekly], ["Team size", inputs.team], ["Estimated project weeks", Number(result.weeks.toFixed(2))],
      ["Annual modeled profit", Number(result.annualProfit.toFixed(2))], ["Assumption", "48 working weeks, full utilization, identical repeated projects; excludes tax and unmodeled costs"],
      [], ["Effort change percent", "Profit at fixed quote", "Margin percent"], ...rows.map(r => [r.delta, Number(r.profit.toFixed(2)), Number(r.margin.toFixed(2))]),
    ], "marginpilot-report.csv");
    setNotice("CSV report downloaded.");
  }
  return <Reveal id="workspace" className="container section workspace-section"><div className="section-heading"><div><p className="eyebrow">THE WORKSPACE / NO SIGN-UP REQUIRED</p><h2>Make the numbers<br /><span className="muted">work for you.</span></h2></div><span className="badge">{tier.toUpperCase()} DEMO · USD</span></div>
    <div className="panel workspace"><div className="workspace-toolbar between"><div className="row"><span className="status-dot" /><span className="mono small">marginpilot / local workspace</span></div><Button onClick={() => { setInputs({ ...DEFAULTS }); setNotice("Inputs reset. Saved scenarios are retained."); }} disabled={!active} className="small"><RotateCcw size={14} />Reset inputs</Button></div>
      {(!storageOK || !inputsOK || !scenariosOK) && <p className="storage-warning" role="status">Browser storage is unavailable or contained invalid data. Calculations still work; changes may only last for this session.</p>}
      <fieldset className="workspace-grid" disabled={!active} aria-busy={!active}><legend className="sr-only">Project pricing workspace</legend><motion.aside layout className="input-panel"><div className="between"><h3>Project inputs</h3><span className="small muted">01—08</span></div><label className="small muted" htmlFor="project-name">Project name</label><input id="project-name" className="name-input" maxLength={60} value={name} onChange={e => setName(e.target.value)} /><div className="row wrap presets">{presets.map(p => <Button className="small" key={p.name} onClick={() => { setInputs({ ...p.inputs }); setName(p.name); setNotice(`${p.name} preset loaded.`); }}>{p.name}</Button>)}</div>
        <Field label="Estimated effort" value={inputs.hours} field="hours" suffix="hrs" onChange={change} /><Field label="Internal hourly cost" value={inputs.rate} field="rate" suffix="USD/hr" onChange={change} /><p className="small muted helper">Use your cost of labor, not your client billing rate.</p><Field label="Direct expenses" value={inputs.expenses} field="expenses" suffix="USD" onChange={change} /><Field label="Allocated project overhead" value={inputs.overhead} field="overhead" suffix="USD" onChange={change} /><Field label="Target profit margin" value={inputs.margin} field="margin" suffix="%" onChange={change} /><Field label="Contingency reserve" value={plus ? inputs.contingency : 0} field="contingency" suffix={plus ? "%" : "Plus"} locked={!plus} onChange={change} /><div className="two-col"><Field label="Hours / week" value={pro ? inputs.weekly : 30} field="weekly" suffix={pro ? "hrs" : "Pro"} locked={!pro} onChange={change} /><Field label="Team size" value={pro ? inputs.team : 1} field="team" suffix={pro ? "people" : "Pro"} locked={!pro} onChange={change} /></div><Button className="primary full" onClick={save}><Save size={16} />Save scenario ({scenarios.length}/{LIMITS[tier]})</Button>
      </motion.aside><div className="result-panel"><div className="tabs" role="tablist" aria-label="Analysis view">{(["quote", "risk", "capacity"] as const).map(t => <Button key={t} role="tab" id={`tab-${t}`} aria-selected={tab === t} aria-controls={`panel-${t}`} tabIndex={tab === t ? 0 : -1} onKeyDown={event => { const tabs = ["quote", "risk", "capacity"] as const; const index = tabs.indexOf(t); let next = index; if (event.key === "ArrowRight") next = (index + 1) % 3; else if (event.key === "ArrowLeft") next = (index + 2) % 3; else if (event.key === "Home") next = 0; else if (event.key === "End") next = 2; else return; event.preventDefault(); setTab(tabs[next]); document.getElementById(`tab-${tabs[next]}`)?.focus(); }} className={tab === t ? "tab active" : "tab"} onClick={() => setTab(t)}>{t === "quote" ? "Quote" : t === "risk" ? "Scope risk" : "Capacity"}{((t === "risk" && !plus) || (t === "capacity" && !pro)) && <LockKeyhole size={12} />}</Button>)}</div>
        <AnimatePresence mode="wait"><motion.div key={tab} role="tabpanel" id={`panel-${tab}`} aria-labelledby={`tab-${tab}`} tabIndex={0} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.15 }}>
          {tab === "quote" && <><div className="quote-block"><p className="eyebrow">YOUR RECOMMENDED PROJECT QUOTE</p><motion.div layout className="quote-number">{money(result.quote)}</motion.div><p className="muted">Built around a {inputs.margin}% target margin{plus ? ` and ${inputs.contingency}% contingency` : ""}.</p></div><div className="metric-grid"><motion.div layout className="mini-card"><p className="small muted">Modeled profit</p><strong className="accent">{money(result.profit)}</strong></motion.div><motion.div layout className="mini-card"><p className="small muted">Effective billing rate</p><strong>{money(result.hourly)}<span className="small muted"> / hr</span></strong></motion.div></div><div className="breakdown"><h4>Every dollar, accounted for.</h4>{[["Labor", inputs.hours * inputs.rate], ["Direct expenses", inputs.expenses], ["Project overhead", inputs.overhead], ["Contingency reserve", result.reserve], ["Target profit", result.profit]].map(([label, value]) => <div className="between ledger-row" key={label}><span className="muted">{label}</span><span className="mono">{money(Number(value))}</span></div>)}<div className="stacked-bar" aria-label="Quote composition">{[inputs.hours * inputs.rate, inputs.expenses, inputs.overhead, result.reserve, result.profit].map((n, i) => <motion.span key={i} animate={{ width: `${n / result.quote * 100}%` }} style={{ background: `var(--chart-${i})` }} />)}</div><p className="small muted">Quote = (labor + expenses + overhead + reserve) ÷ (1 − margin). Profit is after the reserve; taxes and unmodeled costs are excluded.</p></div>{!plus && <Upgrade plan="Plus">Build in a contingency buffer and check what happens when the scope grows.</Upgrade>}</>}
          {tab === "risk" && (plus ? <div className="analysis"><p className="eyebrow">FIXED QUOTE / CHANGING EFFORT</p><h3>What if the work expands?</h3><p className="muted small">The quote stays at {money(result.quote)}. Labor and its contingency reserve change with effort; other costs stay fixed.</p><div className="risk-chart" role="img" aria-label="Profit margin by effort change; exact values are listed below">{rows.map(r => <div className="risk-column" key={r.delta}><span className={r.margin < 0 ? "danger small" : "small"}>{r.margin.toFixed(0)}%</span><div className="bar-track"><motion.div className={r.margin < 0 ? "risk-bar negative" : "risk-bar"} initial={{ height: 0 }} animate={{ height: `${Math.min(100, Math.max(3, Math.abs(r.margin)))}%` }} /></div><span className="small muted">{r.delta > 0 ? "+" : ""}{r.delta}%</span></div>)}</div><table><caption className="sr-only">Scope sensitivity results</caption><thead><tr><th>Effort change</th><th>Profit</th><th>Margin</th></tr></thead><tbody>{rows.map(r => <tr key={r.delta}><td>{r.delta > 0 ? "+" : ""}{r.delta}%</td><td className={r.profit < 0 ? "danger" : ""}>{money(r.profit)}</td><td>{r.margin.toFixed(1)}%</td></tr>)}</tbody></table></div> : <Upgrade plan="Plus">Unlock a seven-point scope stress test. See exactly where overruns erode your margin.</Upgrade>)}
          {tab === "capacity" && (pro ? <div className="analysis"><p className="eyebrow">CAPACITY / 48-WEEK PLANNING MODEL</p><h3>Turn a project into a plan.</h3><div className="metric-grid capacity-metrics">{[["Project duration", `${result.weeks.toFixed(1)} weeks`], ["Team capacity", `${inputs.weekly * inputs.team} hrs/week`], ["Equivalent projects / year", result.annualProjects.toFixed(1)], ["Modeled annual profit", money(result.annualProfit)]].map(([label, value]) => <motion.div layout key={label} className="mini-card"><p className="small muted">{label}</p><strong>{value}</strong></motion.div>)}</div><p className="small muted">Assumes 48 working weeks, full utilization, parallelizable work, and repeated projects with the same cost and scope. This is a planning model, not a revenue forecast. Adjust productive hours to account for selling, admin, and time off.</p></div> : <Upgrade plan="Pro">Adjust productive hours and team size to model delivery time and annual profit.</Upgrade>)}
        </motion.div></AnimatePresence>
        <div className="saved"><div className="between"><h4>Saved scenarios</h4><span className="small muted">{scenarios.length}/{LIMITS[tier]}</span></div>{scenarios.length === 0 && <p className="small muted">Save your first project to revisit the decision.</p>}<AnimatePresence initial={false}>{scenarios.map((s, index) => <motion.div layout initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} key={s.id} className="scenario"><Button className="scenario-load" disabled={index >= LIMITS[tier]} onClick={() => { setInputs({ ...s.inputs }); setName(s.name); setNotice(`Loaded ${s.name}. Results use the current ${tier} tier.`); }}><span>{s.name}</span><span className="mono small muted">{index >= LIMITS[tier] ? "Tier locked" : money(calculate(s.inputs, tier).quote)}</span></Button><Button className="icon-btn" aria-label={`Delete ${s.name}`} onClick={() => { setScenarios(current => current.filter(item => item.id !== s.id)); setNotice(`Deleted ${s.name}.`); }}><Trash2 size={14} /></Button></motion.div>)}</AnimatePresence>{plus && accessible.length > 0 && <div className="comparison"><label htmlFor="compare" className="small muted">Compare current quote with a saved scenario</label><select id="compare" value={compare?.id || ""} onChange={e => setCompareId(e.target.value)}><option value="">Choose a scenario</option>{accessible.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select>{compared && <p className="small">Quote difference: <b>{money(result.quote - compared.quote)}</b> · Profit difference: <b>{money(result.profit - compared.profit)}</b><span className="muted"> (current minus saved, at {tier} settings)</span></p>}</div>}</div>
        <div className="export-row row wrap"><Button disabled={!pro} onClick={exportReport}><Download size={15} />Export CSV {!pro && <LockKeyhole size={12} />}</Button><Button disabled={!pro} onClick={() => { if (pro) window.print(); }}><Printer size={15} />Print report {!pro && <LockKeyhole size={12} />}</Button>{!pro && <span className="small muted">Reports are included in Pro.</span>}</div>
        <p className="notice small" role="status" aria-live="polite">{!active ? "Restoring browser workspace…" : notice || "All calculations run locally. No data leaves this workspace."}</p>
      </div></fieldset>
    </div>
    <article className="print-report"><h1>MarginPilot project report</h1><h2>{name}</h2><p>USD · {tier} demo tier</p><p>Recommended quote: {money(result.quote)} · Modeled profit: {money(result.profit)}</p><p>Effort: {inputs.hours} hours · Labor cost: {money(inputs.rate)}/hour · Expenses: {money(inputs.expenses)} · Overhead: {money(inputs.overhead)}</p><p>Target margin: {inputs.margin}% · Reserve: {money(result.reserve)} · Project duration: {result.weeks.toFixed(1)} weeks</p><p>Annual modeled profit: {money(result.annualProfit)}. Assumes 48 working weeks, full utilization, and identical repeated projects. Excludes taxes and unmodeled costs.</p><table><thead><tr><th>Effort change</th><th>Profit</th><th>Margin</th></tr></thead><tbody>{rows.map(r => <tr key={r.delta}><td>{r.delta}%</td><td>{money(r.profit)}</td><td>{r.margin.toFixed(1)}%</td></tr>)}</tbody></table></article>
  </Reveal>;
}
